# Generated by Django 2.2.1 on 2019-05-28 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disk_size', models.IntegerField(default=0)),
                ('disk_type', models.CharField(default='thin', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Vsphere',
            fields=[
                ('vsphere_host', models.GenericIPAddressField(protocol='ipv4', verbose_name='机房vcenter的地址')),
                ('vsphere_username', models.CharField(max_length=50)),
                ('vsphere_password', models.CharField(max_length=50)),
                ('vsphere_comment', models.CharField(default='9f', max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='VmDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm_name', models.CharField(max_length=200)),
                ('vm_instance_UUID', models.CharField(max_length=200)),
                ('vm_bios_UUID', models.CharField(max_length=200)),
                ('vm_path_to_vm', models.CharField(max_length=200)),
                ('vm_guest_os_name', models.CharField(max_length=100)),
                ('datacenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adddisk.Vsphere')),
            ],
        ),
    ]
